name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^chore\(release\)'
          flags: 'gm'
          error: 'Skipping for non release commit.'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Build library
        run: yarn build

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          HUSKY: 0
